### ISSUE TITLE
Setup Web Server

### ISSUE THREAD

**Issue by JPautz** [cpe308-309/polypath-api#93]
Setup a web server to serve the angular app to the client. Will interact with the database through API calls in the angular app.

**Comment by macrivello** [comment]
1. Create polypath-web repo.
2. Create polypath-web heroku server.
3. Configure travis CI for angular2 build.

**Comment by macrivello** [comment]
1. I created the polypath-web repo https://github.com/cpe308-309/polypath-web
2. I created the polypath-web heroku server https://dashboard.heroku.com/apps/polypath-web
3. Hooked up travis CI, but not running any tests.
